# Generated by Django 5.2.6 on 2025-09-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('car_name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('registration_no', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
    ]
